### ISSUE TITLE
Implements SPAKE1 not SPAKE2

### ISSUE THREAD

**Issue by wbl** [warner/python-spake2#1]
If you're using my old draft you should know it has a big mistake. SPAKE2 includes the password to be secure in concurrent settings. See http://www.di.ens.fr/~mabdalla/papers/AbPo05a-letter.pdf for details.

**Comment by warner** [comment]
I think we're good, the password is included in the transcript (which is then hashed to compute the session key): https://github.com/warner/python-spake2/blob/master/spake2/spake2.py#L157 and https://github.com/warner/python-spake2/blob/master/spake2/spake2.py#L236 . Could you double-check and close this issue if you agree that we're implementing SPAKE2 correctly?

**Comment by wbl** [comment]
You are good: I was mislead by the comments.
