### ISSUE TITLE
No released version with recent changes

### ISSUE THREAD

**Issue by emilazy** [warner/python-spake2#20]
Hi @meejah! Following up on https://github.com/magic-wormhole/magic-wormhole/issues/534, is there any progress getting a release out with the `cryptography` migration and Python 3.12 fixes? From the Nixpkgs point of view we’d be happy with any of a PyPI release, a GitHub tag, or even just a statement that the current Git HEAD should be okay to ship to users as part of Magic Wormhole.

**Comment by meejah** [comment]
`v0.9` is tagged, and is on PyPI.

Note that this one is signed by me, if that affects your build process.
